README.md
ensure.ts
ensure_test.ts
is.ts
is_test.ts

Now users can use `isLike` or `ensureLike` to check complex tuple or struct like:
```typescript
Deno.test("isLike returns true/false on tuple", () => {
const ref = ["", 0, ""];
assertEquals(isLike(ref, ["", 0, ""]), true);
assertEquals(isLike(ref, ["Hello", 100, "World"]), true);
assertEquals(isLike(ref, ["Hello", 100, "World", "foo"]), false);
assertEquals(isLike(ref, [0, 0, 0]), false);
assertEquals(isLike(ref, ["", "", ""]), false);
assertEquals(isLike(ref, [0, "", 0]), false);
});
```
```typescript
Deno.test("ensureLike does it's job on struct", () => {
const ref = { foo: "", bar: 0 };
ensureLike(ref, { foo: "", bar: 0 });
ensureLike(ref, { foo: "", bar: 0, hoge: "" });
assertThrows(() => ensureLike(ref, {}));
assertThrows(() => ensureLike(ref, { foo: "" }));
assertThrows(() => …
```

Add `isLike` and `ensureLike` for complex tuple/struct

---

README.md
ensure.ts
ensure_test.ts
is.ts
is_test.ts

Added the ability to compare objects/arrays containing bool types with isLike.
To achieve this, I have added two functions and their corresponding tests.
- `isBoolean(x: unknown): x is boolean` : returns true if and only if `x` is boolean
- `ensureBoolean(x: unknown): asserts x is boolean` : ensures `x` is boolean

Support for comparing objects with boolean type in `isLike` function

---

is.ts
is_test.ts

```ts
import is from "./is.ts";
const a: unknown = [0, 1, 2, 3, 4];
if (is.UniformTupleOf(5)(a)) {
// a is narrowed to [unknown, unknown, unknown, unknown, unknown]
const _: readonly [unknown, unknown, unknown, unknown, unknown] = a;
}
if (is.UniformTupleOf(5, is.Number)(a)) {
// a is narrowed to [number, number, number, number, number]
const _: readonly [number, number, number, number, number] = a;
}
```

:+1: Add `isUniformTupleOf`

---

is.ts
is_bench.ts
is_test.ts

Example
```ts
import is from "./is.ts";
const predObj = {
a: is.Number,
b: is.String,
c: is.OptionalOf(is.Boolean),
};
const a: unknown = { a: 0, b: "a" };
if (is.ObjectOf(predObj)(a)) {
// a is narrowed to { a: number, b: string, c?: boolean }
const _: { a: number, b: string, c?: boolean } = a;
}
```

Allow `isObjectOf` to specify an optional property

---

is_bench.ts

Add benchmarks for predefining predicates by `is*Of` higher-order functions.

:memo: Add benchamrk for pre-defined predicates

---

is.ts
is_bench.ts
is_test.ts

This is a friend of `isOneOf`.

👍 Add `isAllOf`

---

is_test.ts
scripts/build_npm.ts
util_test.ts

The output of `make update` is
```
/home/runner/work/deno-unknownutil/deno-unknownutil/scripts/build_npm.ts
[1/1] Looking for releases: https://deno.land/x/dnt@0.37.0/mod.ts
[1/1] Attempting update: https://deno.land/x/dnt@0.37.0/mod.ts -> 0.38.1
[1/1] Update successful: https://deno.land/x/dnt@0.37.0/mod.ts -> 0.38.1
/home/runner/work/deno-unknownutil/deno-unknownutil/is_bench.ts
/home/runner/work/deno-unknownutil/deno-unknownutil/is.ts
/home/runner/work/deno-unknownutil/deno-unknownutil/mod.ts
/home/runner/work/deno-unknownutil/deno-unknownutil/is_test.ts
[1/2] Looking for releases: https://deno.land/std@0.192.0/testing/asserts.ts
[1/2] Attempting update: https://deno.land/std@0.192.0/testing/asserts.ts -> 0.200.0
[1/2] Update successful: https://deno.land/std@0.192.0/testing/asserts.ts …
```

:package: Update Deno dependencies

---

util.ts
util_test.ts

Now the default assertion error message contains the information about the type of value, predicate name, and the value itself.
Additionally, users can change the factory function with `setAssertMessageFactory`.

:+1: Improve the assertion error message

---

README.md
is.ts
is_test.ts
util_test.ts

Now users can infer `T` from `Predicate<T>` so that they don't need to define type definition twice
```ts
const isArticle = is.ObjectOf({
title: is.String,
body: is.String,
refs: is.ArrayOf(is.OneOf([
is.String,
is.ObjectOf({
name: is.String,
url: is.String,
}),
])),
});
type Article = {
title: string;
body: string;
refs: (string | {
name: string;
url: string;
})[];
};
```
```ts
const isArticle = is.ObjectOf({
title: is.String,
body: is.String,
refs: is.ArrayOf(is.OneOf([
is.String,
is.ObjectOf({
name: is.String,
url: is.String,
}),
])),
});
type Article = PredicateType<typeof isArticle>;
```

:+1: Add `PredicateType<P>` to infer `T` of `Predicate<T>`

---

__snapshots__/inspect_test.ts.snap
__snapshots__/is_test.ts.snap
inspect.ts
inspect_test.ts
is.ts
is_test.ts
scripts/build_npm.ts

```
error: Uncaught AssertError: Expected a value that satisfies the predicate anonymous predicate, got object: {
"tile": "Awesome article",
"body": "This is an awesome article",
"refs": [
{
"name": "Deno",
"url": "https://deno.land/"
},
"https://github.com"
]
}
throw new AssertError(
^
at assert (file:///Users/alisue/ghq/github.com/lambdalisue/deno-unknownutil/util.ts:85:11)
at file:///Users/alisue/ghq/github.com/lambdalisue/test.ts:22:1
```
```
error: Uncaught AssertError: Expected a value that satisfies the predicate isObjectOf({
title: isString,
body: isString,
refs: isArrayOf(isOneOf([
isString,
isObjectOf({
name: isString,
url: isString
})
]))
}), got object: {
"tile": "Awesome article",
"body": "This is an awesome article",
"refs": [
{
"name": "Deno",
"url": "https://deno.land/"
}, …
```

:+1: Add name property to type predicate functions

---

is.ts

I want to be able to check the deprecated usage of `isObjectOf()`.

:+1: Add @deprecated to `isObjectOf()` that with `options.strict`

---

is.ts
is_test.ts

Sometimes I want to use a function object with properties extended to it.

`isObjectOf` allows function object

---

__snapshots__/is_test.ts.snap
_typeutil.ts
is.ts
is_test.ts

Fixes #68
It's close to the functionality of the old `AllOf`.
Allow only one element?
```ts
const isMyObj = is.IntersectionOf([
is.ObjectOf({a: is.String}),
]);
```
Currently...
- The type allows only one or more elements.
- The implementation also works with 0 elements.
- In that case, the Predicate will always return `true`.

:+1: `isIntersectionOf` allows anything other than `isObjectOf`

---

__snapshots__/is_test.ts.snap
is.ts
is_test.ts

I want to validate method arguments with optional parameters.
- `isTupleOf()`: the length of the tuple is fixed.
```ts
const a: unknown = ["a"];
if (is.TupleOf([is.String, is.Optional(is.Number)] as const)(a)) {
// don't reach here
const _: [string, number | undefined] = a;
}
```
- `isParametersOf()`: the tuple is truncated length if trailing predicates are optional.
```ts
const a: unknown = ["a"];
if (is.ParametersOf([is.String, is.Optional(is.Number)] as const)(a)) {
// reach here
const _: [string, number?] = a;
}
```
If there is a better name, please suggest.

:+1: Add `isParametersOf`

---

is/object_of.ts
is/object_of_test.ts

fix[isObjectOf]: no discover prototype properties

---

__snapshots__/_inspect_test.ts.snap
_inspect.ts
_inspect_test.ts

Note that there is no way to get the string keys and symbol keys in order, so we first enumerate the string keys, then the symbol keys.

feat[inspect]: inspects record with symbol properties

---

deno.jsonc

fix: remove `is/mod` from `deno.jsonc`

---

is/__snapshots__/record_object_of_test.ts.snap
is/record_object_of.ts
is/record_object_of_test.ts

Contains bug fixes. See below comments.

feat[isRecordObjectOf]: checks own symbol key properties

---

is/__snapshots__/record_of_test.ts.snap
is/record_of.ts
is/record_of_test.ts

Contains bug fixes. See comments in #110.

feat[isRecordOf]: checks own symbol key properties

---

is/__snapshots__/parameters_of_test.ts.snap
is/__snapshots__/tuple_of_test.ts.snap
is/parameters_of.ts
is/parameters_of_test.ts
is/tuple_of.ts
is/tuple_of_test.ts

fix[isTupleOf,isParametersOf]: rename predElse to predRest

---

is/__snapshots__/tuple_of_test.ts.snap
is/mod.ts
is/tuple_of.ts
is/tuple_of_test.ts

Typescript tuple types can define leading or middle rest elements.
Added corresponding overloads to `isTupleOf()`.

feat[isTupleOf]: add overloads to leading/middle rest elements

---

deno.jsonc
is/custom_jsonable.ts
is/custom_jsonable_bench.ts
is/custom_jsonable_test.ts
is/jsonable.ts
is/jsonable_bench.ts
is/jsonable_test.ts
is/mod.ts

If we strictly adhere to [the description of `JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description), the `isJsonable` function would be implemented like this.
However, I’m not sure if this aligns with what @Milly originally intended. What we might actually need is a predicate function to determine if an object implements a `toJSON` function.
@Milly What do you think?

feat: add `isCustomJsonable` and `isJsonable`
